<MainGui>:
    sm: sm

    BoxLayout:
        orientation: 'vertical'

        Spinner:
            height: 35
            size_hint_y: None
            #size_hint: None,1
            text: 'Music'
            values: ['Music', 'Radio']
            #height: '108sp'
            #background_color: [0,1,0,1]
            on_text: root.switch_screen(args)

        ScreenManager:
            id: sm
            size_hint_y: 0.6

<MusicScreen>:
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            height: 35
            size_hint_y: None

            Label:
                text: ''

            Label:
                text: 'Music Library'

            Label:
                text: 'Playlists'

        BoxLayout:
            FileChooserListView:
                id: listfilechooser
                on_submit: root.load(listfilechooser.path, listfilechooser.selection)

            TextInput:
                id: t_music_library
                readonly: True

            TextInput:
                id: t_playlists
                readonly: True

        #Slider:
        #    min: 0
        #    max: 1
        #    size: 350, 10
        #    #pos: 400, 30
        #    step: 0.01
        #    value: 0.5
        #    on_value: print("Still to implement")

        BoxLayout:
            size_hint_y: None
            height: 30

            #Button:
                #text: 'Load song'
                #on_release: root.show_load()
            Button:
                text: 'Play/Pause'
                #size: 100, 75
                #pos: 10, 0
                on_press: root.play_pause_audio()
            Button:
                text: 'Stop'
                #size: 100, 75
                #pos: 110, 0
                on_press: root.stop_audio()
            Button:
                text: 'Reload'
                #size: 100, 75
                #pos: 210, 0
                on_press: root.reload_audio()
            Slider:
                min: 0
                max: 1
                #size: 350, 10
                #pos: 400, 30
                step: 0.01
                value: 0.5
                on_value: root.set_volume(self.value)

<RadioScreen>:
    rs_layout: rs_layout

    BoxLayout:

        BoxLayout:
            id: rs_layout
            orientation: 'vertical'
            padding: 30
            spacing: 30

        Label:
            text: 'Label'

#        Slider:
#            min: 0
#            max: 1
#            #size: 350, 10
#            #pos: 400, 30
#            step: 0.01
#            value: 0.5
#            on_value: root.set_volume(self.value)

#        Button:
#            text: 'Radio Deejay'
#            on_press: root.play_station(self.text)
#
#        Button:
#            text: 'RTL 102.5'
#            on_press: root.play_station(self.text)
#
#        Button:
#            text: 'Virgin Radio'
#            on_press: root.play_station(self.text)

#<MusicScreen>:
#    BoxLayout:
#        orientation: 'vertical'
#
#        Button:
#            text: '1'
#
#        Button:
#            text: '2'
#
#        Button:
#            text: '3'


#<LoadDialog>:
#    BoxLayout:
#        size: root.size
#        pos: root.pos
#        orientation: "vertical"
#        FileChooserIconView:
#            id: filechooser
#
#        BoxLayout:
#            size_hint_y: None
#            height: 30
#            Button:
#                text: "Cancel"
#                on_release: root.cancel()
#
#            Button:
#                text: "Load"
#                on_release: root.load(filechooser.path, filechooser.selection)
#