<MainGui>:
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            height: 35
            size_hint_y: None

            Label:
                text: ''

            Label:
                text: 'Music Library'

            Label:
                text: 'Playlists'

        BoxLayout:
            FileChooserListView:
                id: listfilechooser
                on_submit: root.load(listfilechooser.path, listfilechooser.selection)

            TextInput:
                id: music_library
                readonly: True

            TextInput:
                id: playlists
                readonly: True

        #Slider:
        #    min: 0
        #    max: 1
        #    size: 350, 10
        #    #pos: 400, 30
        #    step: 0.01
        #    value: 0.5
        #    on_value: print("Still to implement")

        BoxLayout:
            size_hint_y: None
            height: 30

            #Button:
                #text: 'Load song'
                #on_release: root.show_load()
            Button:
                text: 'Play/Pause'
                #size: 100, 75
                #pos: 10, 0
                on_press: root.play_pause_audio()
            Button:
                text: 'Stop'
                #size: 100, 75
                #pos: 110, 0
                on_press: root.stop_audio()
            Button:
                text: 'Reload'
                #size: 100, 75
                #pos: 210, 0
                on_press: root.reload_audio()
            Slider:
                min: 0
                max: 1
                #size: 350, 10
                #pos: 400, 30
                step: 0.01
                value: 0.5
                on_value: root.set_volume(self.value)


#<LoadDialog>:
#    BoxLayout:
#        size: root.size
#        pos: root.pos
#        orientation: "vertical"
#        FileChooserIconView:
#            id: filechooser
#
#        BoxLayout:
#            size_hint_y: None
#            height: 30
#            Button:
#                text: "Cancel"
#                on_release: root.cancel()
#
#            Button:
#                text: "Load"
#                on_release: root.load(filechooser.path, filechooser.selection)
#